ArtGallery.WebApp/Controllers/AuctionsController.cs
using ArtGallery.Data.Entities;
using ArtGallery.ViewModel.Catalog.Auctions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using ArtGallery.WebApp.Models;

namespace ArtGallery.WebApp.Controllers
{
    public class AuctionsController : Controller
    {
        private readonly string url = "http://localhost:5000/api/Auctions/";
        private HttpClient httpClient = new HttpClient();

        // Going 
        [HttpGet]
        public IActionResult GetAuctionGoing(int pg = 1)
        {
            IEnumerable<Auction> listAuctions = JsonConvert.DeserializeObject<IEnumerable<Auction>>(httpClient.GetStringAsync(url + "GetAllAuctions").Result);
            //HttpContext.Session.SetString("listAuctions", JsonConvert.SerializeObject(listAuctions));
            //var aucComming = listAuctions.Where(c => c.StartDateTime > DateTime.Now).ToList();
            var aucGoing = listAuctions.Where(c => c.StartDateTime < DateTime.Now && c.EndDateTime > DateTime.Now).OrderByDescending(c=>c.Id).ToList();
            //var aucEnded = listAuctions.Where(c => c.EndDateTime < DateTime.Now).ToList();
            // Check
            const int pageSize2 = 6;
            if (pg < 1)
                pg = 1;
            int recsCount2 = aucGoing.Count();
            var pager2 = new Pager(recsCount2, pg, pageSize2);
            int recSkip2 = (pg - 1) * pageSize2;
            var data2 = aucGoing.Skip(recSkip2).Take(pager2.PageSize).ToList();
            //
            this.ViewBag.Pager = pager2;
            this.ViewBag.aucGoing = data2;
            return View();
        }

        // Comming
        [HttpGet]
        public IActionResult GetAuctionComming(int pg = 1)
        {
            IEnumerable<Auction> listAuctions = JsonConvert.DeserializeObject<IEnumerable<Auction>>(httpClient.GetStringAsync(url + "GetAllAuctions").Result);
            //HttpContext.Session.SetString("listAuctions", JsonConvert.SerializeObject(listAuctions));
            var aucComming = listAuctions.Where(c => c.StartDateTime > DateTime.Now).OrderByDescending(c=>c.Id).ToList();
            // Check
            const int pageSize = 6;
            if (pg < 1)
                pg = 1;
            int recsCount = aucComming.Count();
            var pager = new Pager(recsCount, pg, pageSize);
            int recSkip = (pg - 1) * pageSize;
            var data = aucComming.Skip(recSkip).Take(pager.PageSize).ToList();
            //
            this.ViewBag.Pager = pager;
            this.ViewBag.aucComming = data;
            return View();
        }

        // Ended
        [HttpGet]
        public IActionResult GetAuctionEnded(int pg = 1)
        {
            IEnumerable<Auction> listAuctions = JsonConvert.DeserializeObject<IEnumerable<Auction>>(httpClient.GetStringAsync(url + "GetAllAuctions").Result);
            //HttpContext.Session.SetString("listAuctions", JsonConvert.SerializeObject(listAuctions));
            var aucEnded = listAuctions.Where(c => c.EndDateTime < DateTime.Now).OrderByDescending(c=>c.Id).ToList();
            // Check
            const int pageSize3 = 6;
            if (pg < 1)
                pg = 1;
            int recsCount3 = aucEnded.Count();
            var pager3 = new Pager(recsCount3, pg, pageSize3);
            int recSkip3 = (pg - 1) * pageSize3;
            var data3 = aucEnded.Skip(recSkip3).Take(pager3.PageSize).ToList();
            //
            this.ViewBag.Pager = pager3;
            this.ViewBag.aucEnded = data3;
            return View();
        }

        [Authorize(Roles = "User")]
        [HttpGet]
        public IActionResult AuctionRoom(int id)
        {
            Auction auction = JsonConvert.DeserializeObject<Auction>(httpClient.GetStringAsync(url + "GetAuction/" + id).Result);
            ViewBag.auc = auction;



            //IEnumerable<Auction> list = JsonConvert.DeserializeObject<IEnumerable<Auction>>(HttpContext.Session.GetString("listAuctions"));
            //HttpContext.Session.Remove("listAuctions");
            //list.SingleOrDefault(c => c.Id.Equals(id));
            //HttpContext.Session.SetString("listAuctions", JsonConvert.SerializeObject(list.SingleOrDefault(c => c.Id.Equals(id))));
            //IEnumerable<Auction> listAuctions = JsonConvert.DeserializeObject<IEnumerable<Auction>>(httpClient.GetStringAsync(url + "GetAllAcutions").Result);
            return View(/*listAuctions.SingleOrDefault(c => c.Id.Equals(id))*/);
        }
        [Authorize(Roles = "User")]
        [HttpPost]
        public async Task<IActionResult> AuctionRoom(InsertAmountInAuctionRequest request)
        {
            foreach (var item in User.Claims.ToList().Where(c => c.Type.Equals("UserId")))
            {
                request.AccountId = item.Value.ToString();
            }
            if (ViewBag.auc==null)
            {
                ViewBag.auc = JsonConvert.DeserializeObject<Auction>(httpClient.GetStringAsync(url + "GetAuction/" + request.AuctionId).Result);
            }
            if (!ModelState.IsValid) return View();
            AmountInAuction Aauc = new AmountInAuction
            {
                AuctionId = request.AuctionId,
                NewPrice = request.NewPrice,
                AccountId = request.AccountId
            };
            var json = JsonConvert.SerializeObject(Aauc);
            var httpContent = new StringContent(json, Encoding.UTF8, "application/json");
            var result = JsonConvert.DeserializeObject<bool>(await httpClient.PostAsync(url + "InsertAmount", httpContent).Result.Content.ReadAsStringAsync());
            TempData["msgroomauc"] = "The amount you bet is: " + request.NewPrice.ToString() + "$";
            return RedirectToAction("AuctionRoom");
        }
        [HttpGet]
        public IActionResult RoomEnded(int id)
        {
            try
            {
                ProfileUser profileUsers = JsonConvert.DeserializeObject<ProfileUser>(httpClient.GetStringAsync(url + "GetWinner/" + id).Result);
                TempData["msgroomauc"] = $"Auction ended. We will contact Mr.{profileUsers.FullName} via gmail";
                string urlmail = "http://localhost:5000/api/Mail/";
                var request = JsonConvert.DeserializeObject<bool>(httpClient.GetStringAsync(urlmail + "AuctionWiner/" + id).Result);
            }
            catch (Exception)
            {

                return BadRequest();
            }
            return RedirectToAction("GetAuctionEnded");
        }
    }
}
    

ArtGallery.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>OAG - Online Art Gallery</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="~/images/favicon.png">
    <!--custom css-->
    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/style.css" rel="stylesheet" type="text/css" />
    <link href="~/css/site.css" rel="stylesheet" type="text/css" />
    @*<link href="~/css/loading.css" rel="stylesheet" type="text/css" />*@
    <link href="~/css/edit14.css" rel="stylesheet" type="text/css" />
    <!--js --->
    <script src="~/js/jquery-2.1.1.min.js" type="text/javascript"></script>
    <script src="~/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="~/js/custom.js" type="text/javascript"></script>
    @*<script src="~/js/site.js" type="text/javascript"></script>*@
</head>
<body>
    @*<div id="loader"></div>
    <div style="display:none;" id="myDiv" class="animate-bottom">*@
        <!--headerblock-->
        <header>
            <div class="top-line">
                <div class="container top-box">
                    <div class="leftside">
                        <div class="language-block">
                            <form>
                                <div class="dropdown">
                                    <span data-toggle="dropdown" class="toggle">ENGLISH</span>
                                </div>
                            </form>
                        </div>
                        <div class="currency-block">
                            <form>
                                <div class="dropdown">
                                    <span data-toggle="dropdown" class="toggle">US DOLLAR</span>
                                </div>
                            </form>
                        </div>
                        <div class="social-icon-block">
                            <ul class="social-list">
                                <li><a><i class="fa fa-phone fa-1x" aria-hidden="true"></i> (+84) 0987654321</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="rightside">
                        <div class="top-button">
                            <a><i class="fa fa-bell" aria-hidden="true"></i></a>
                        </div>
                        <div class="top-button">
                            <a><i class="fa fa-heart-o" aria-hidden="true"></i></a>
                        </div>
                        <div class="top-button">
                            <div class="dropdown">
                                <span class="toggle" data-toggle="dropdown" aria-expanded="false">
                                    <i class="fa fa-user"></i>
                                </span>
                                <ul class="dropdown-menu">
                                    <!-- Check User -->
                                    @{ var user = User.Identity.Name;
                                        if (user == null)
                                        {
                                            <li><a asp-action="Logout" asp-controller="Users">Login</a></li>
                                            <li><a asp-action="Register" asp-controller="Users">Register</a></li>
                                        }
                                        else
                                        {
                                            <li><a asp-action="Profile" asp-controller="Users">@user</a></li>
                                            <li><a asp-action="Logout" asp-controller="Users">Logout</a></li>
                                        }
                                    }
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!---logo--->
            <div class="container">
                <div class="leftside">
                    <div class="logo">
                        <a asp-action="Home" asp-controller="Home"><img src="~/images/logo3.png" alt="art-design" class="img-responsive" width="140" /></a>
                    </div>
                </div>
            </div>
            <!---navbar--->
            <div class="container">
                <div class="row">
                    <div class="col-md-3 col-sm-2"></div>
                    <div class="col-md-7 col-sm-7 col-xs-7 rightside-add-space">
                        <nav class="navbar navbar-inverse menu-bar">
                            <div class="container-fluid">
                                <div class="navbar-header">
                                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                    </button>
                                </div>
                                <div class="collapse navbar-collapse" id="myNavbar">
                                    <ul class="nav navbar-nav">
                                        <li><a asp-action="Home" asp-controller="Home">Home</a></li>
                                        <li><a asp-action="GetProduct" asp-controller="ManagerStores">Gallery</a></li>
                                        <li><a asp-action="GetAuctionGoing" asp-controller="Auctions">Auctions</a></li>
                                        <li>@Html.ActionLink("About Us", "AboutUs", "Home")</li>
                                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                                    </ul>
                                </div>
                            </div>
                        </nav>
                    </div>
                    <a asp-action="GetCart" asp-controller="Carts">
                        <div class="col-md-2 col-sm-3 col-xs-5 leftside-remove-space">
                            <div class="btn-group btn-block box-cart">
                                <img src="~/images/shopping-cart.png" width="30" />
                                <span>Carts</span>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </header>
        <!--end of header block-->
        <!--end sidebar-->
        @RenderBody()
        <!--bottom block-->
        <div class="container">
            <div class="row">
                <div class="bottom-block">
                    <div class="col-md-4">
                        <div class="bottom-block-heading"><h4>Free Shopping <span><i class="fa fa-truck"></i></span></h4></div>
                        <div class="bottom-block-description">
                            <p>Free delivery on all orders over $199</p>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="bottom-block-heading"><h4>Money back garanty <span><i class="fa fa-money"></i></span></h4></div>
                        <div class="bottom-block-description">
                            <p>we offer 15 day easy return</p>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="bottom-block-heading"><h4>Online support 24/7 <span><i class="fa fa-phone-square"></i></span></h4></div>
                        <div class="bottom-block-description">
                            <p>Our operators are available 24/7</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--end bottom block-->
        <hr class="margin-top hidden-xs" />
        <!--footer block--->
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-sm-3">
                        <div class="footer-block">
                            <h4>Information <i class="fa fa-angle-up"></i></h4>
                            <ul class="list-unstyled">
                                <li>@Html.ActionLink("About Us", "AboutUs", "Home")</li>
                                <li><a>Privacy Policy</a></li>
                                <li><a>Terms &amp; Conditions</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="footer-block">
                            <h4>Customer Service <i class="fa fa-angle-up"></i></h4>
                            <ul class="list-unstyled">
                                <li>@Html.ActionLink("Contact Us", "Contact", "Home")</li>
                                <li><a>Returns</a></li>
                                <li><a>Site Map</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="footer-block">
                            <h4>Extras <i class="fa fa-angle-up"></i></h4>
                            <ul class="list-unstyled">
                                <li><a>Brands</a></li>
                                <li><a>Affiliates</a></li>
                                <li><a>Specials</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="footer-block">
                            <h4>My Account <i class="fa fa-angle-up"></i></h4>
                            <ul class="list-unstyled">
                                <li><a>My Account</a></li>
                                <li><a>Order History</a></li>
                                <li><a>Wish List</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="copyright">
                <div class="container">
                    <!--Do not remove Backlink from footer of the template. To remove it you can purchase the Backlink !-->
                    © 2022 All right reserved. Designed by
                    <a href="" target="_blank">OAG.</a>
                </div>
            </div>
        </footer>
        <!--end footer block--->
        <a style="display: none" href="javascript:void(0);" class="scrollTop back-to-top" id="back-to-top">
            <i class="fa fa-chevron-up"></i>
        </a>
    @*</div>*@
</body>
</html>

ArtGallery.WebApp/Views/Shared/_Layout1.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>OAG - Online Art Gallery</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="~/images/favicon.png">
    <!--custom css-->
    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/style.css" rel="stylesheet" type="text/css" />
    <link href="~/css/site.css" rel="stylesheet" type="text/css" />
    @*<link href="~/css/loading.css" rel="stylesheet" type="text/css" />*@
    <link href="~/css/edit14.css" rel="stylesheet" type="text/css" />
    <!--js --->
    <script src="~/js/jquery-2.1.1.min.js" type="text/javascript"></script>
    <script src="~/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="~/js/custom.js" type="text/javascript"></script>
    @*<script src="~/js/site.js" type="text/javascript"></script>*@
</head>
<body>
    @*<div id="loader"></div>
    <div style="display:none;" id="myDiv" class="animate-bottom">*@
        <!--headerblock-->
        <header>
            <div class="top-line">
                <div class="container top-box">
                    <div class="leftside">
                        <div class="language-block">
                            <form>
                                <div class="dropdown">
                                    <span data-toggle="dropdown" class="toggle">ENGLISH</span>
                                </div>
                            </form>
                        </div>
                        <div class="currency-block">
                            <form>
                                <div class="dropdown">
                                    <span data-toggle="dropdown" class="toggle">
                                        US DOLLAR
                                    </span>
                                </div>
                            </form>
                        </div>
                        <div class="social-icon-block">
                            <ul class="social-list">
                                <li><a><i class="fa fa-phone fa-1x" aria-hidden="true"></i> (+84) 0987654321</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="rightside">
                        <div class="top-button">
                            <a><i class="fa fa-bell" aria-hidden="true"></i></a>
                        </div>
                        <div class="top-button">
                            <a><i class="fa fa-heart-o" aria-hidden="true"></i></a>
                        </div>
                        <div class="top-button">
                            <div class="dropdown">
                                <span class="toggle" data-toggle="dropdown" aria-expanded="false">
                                    <i class="fa fa-user"></i>
                                </span>
                                <ul class="dropdown-menu">
                                    <!-- Check User -->
                                    @{ var user = User.Identity.Name;
                                        if (user == null)
                                        {
                                            <li><a asp-action="Logout" asp-controller="Users">Login</a></li>
                                            <li><a asp-action="Register" asp-controller="Users">Register</a></li>
                                        }
                                        else
                                        {
                                            <li><a asp-action="Profile" asp-controller="Users">@user</a></li>
                                            <li><a asp-action="Logout" asp-controller="Users">Logout</a></li>
                                        }
                                    }
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!---logo--->
            <div class="container">
                <div class="leftside">
                    <div class="logo">
                        <a asp-action="Home" asp-controller="Home"><img src="~/images/logo3.png" alt="art-design" class="img-responsive" width="140" /></a>
                    </div>
                </div>
            </div>
            <!---navbar--->
            <div class="container">
                <div class="row">
                    <!-- <div class="col-md-3 col-sm-2"></div> -->
                    <div class="col-md-12 col-sm-12 col-xs-12 rightside-add-space">
                        <nav class="navbar navbar-inverse menu-bar">
                            <div class="container-fluid">
                                <div class="navbar-header">
                                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                    </button>
                                </div>
                                <div class="collapse navbar-collapse" id="myNavbar">
                                    <ul class="nav navbar-nav">
                                        <li><a asp-action="Home" asp-controller="Home">Home</a></li>
                                        <li><a asp-action="GetProduct" asp-controller="ManagerStores">Gallery</a></li>
                                        <li><a asp-action="GetAuctionGoing" asp-controller="Auctions">Auctions</a></li>
                                        <li>@Html.ActionLink("About Us", "AboutUs", "Home")</li>
                                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                                    </ul>
                                </div>
                            </div>
                        </nav>
                    </div>
                </div>
            </div>
        </header>
        <!--end of header block-->
        <!--end sidebar-->
        @RenderBody()
        <!--bottom block-->
        <div class="container">
            <div class="row">
                <div class="bottom-block">
                    <div class="col-md-4">
                        <div class="bottom-block-heading"><h4>Free Shopping <span><i class="fa fa-truck"></i></span></h4></div>
                        <div class="bottom-block-description">
                            <p>Free delivery on all orders over $199</p>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="bottom-block-heading"><h4>Money back garanty <span><i class="fa fa-money"></i></span></h4></div>
                        <div class="bottom-block-description">
                            <p>we offer 15 day easy return</p>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="bottom-block-heading"><h4>Online support 24/7 <span><i class="fa fa-phone-square"></i></span></h4></div>
                        <div class="bottom-block-description">
                            <p>Our operators are available 24/7</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--end bottom block-->
        <hr class="margin-top hidden-xs" />
        <!--footer block--->
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-sm-3">
                        <div class="footer-block">
                            <h4>Information <i class="fa fa-angle-up"></i></h4>
                            <ul class="list-unstyled">
                                <li>@Html.ActionLink("About Us", "AboutUs", "Home")</li>
                                <li><a>Privacy Policy</a></li>
                                <li><a>Terms &amp; Conditions</a></li>
                            </ul>

                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="footer-block">
                            <h4>Customer Service <i class="fa fa-angle-up"></i></h4>
                            <ul class="list-unstyled">
                                <li>@Html.ActionLink("Contact Us", "Contact", "Home")</li>
                                <li><a>Returns</a></li>
                                <li><a>Site Map</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="footer-block">
                            <h4>Extras <i class="fa fa-angle-up"></i></h4>
                            <ul class="list-unstyled">
                                <li><a>Brands</a></li>
                                <li><a>Affiliates</a></li>
                                <li><a>Specials</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="footer-block">
                            <h4>My Account <i class="fa fa-angle-up"></i></h4>
                            <ul class="list-unstyled">
                                <li><a>My Account</a></li>
                                <li><a>Order History</a></li>
                                <li><a>Wish List</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="copyright">
                <div class="container">
                    <!--Do not remove Backlink from footer of the template. To remove it you can purchase the Backlink !-->
                    © 2022 All right reserved. Designed by
                    <a href="" target="_blank">OAG.</a>
                </div>
            </div>
        </footer>
        <!--end footer block--->
        <a style="display: none" href="javascript:void(0);" class="scrollTop back-to-top" id="back-to-top">
            <i class="fa fa-chevron-up"></i>
        </a>
    @*</div>*@
</body>
</html>