ArtGallery.AdminApp/Controllers/CategoryManagerController.cs
using ArtGallery.Data.Entities;
using ArtGallery.ViewModel.System.Admin;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using ArtGallery.AdminApp.Models;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;

namespace ArtGallery.AdminApp.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CategoryManagerController : Controller
    {
        // Check
        private readonly string url = "http://localhost:5000/api/CategoriesManager/";
        private readonly HttpClient httpClient = new HttpClient();

        [HttpGet]
        public IActionResult Index(int pg = 1)
        {
            var model = JsonConvert.DeserializeObject<IEnumerable<Category>>(httpClient.GetStringAsync(url).Result);
            model = model.OrderByDescending(c => c.Id).ToList();
            // Check 
            const int pageSize = 10;
            if (pg < 1)
                pg = 1;
            int recsCount = model.Count();
            var pager = new Pager(recsCount, pg, pageSize);
            int recSkip = (pg - 1) * pageSize;
            var data = model.Skip(recSkip).Take(pager.PageSize).ToList();
            this.ViewBag.Pager = pager;
            CategoryModelView categoryModelView = new CategoryModelView { Categories = data };
            return View(categoryModelView);
        }

        [HttpPost]
        public IActionResult Index(string name, int pg = 1)
        {
            var model = JsonConvert.DeserializeObject<IEnumerable<Category>>(httpClient.GetStringAsync(url + name).Result);
            // Check 
            const int pageSize = 10;
            if (pg < 1)
                pg = 1;
            int recsCount = model.Count();
            var pager = new Pager(recsCount, pg, pageSize);
            int recSkip = (pg - 1) * pageSize;
            var data = model.Skip(recSkip).Take(pager.PageSize).ToList();
            this.ViewBag.Pager = pager;
            CategoryModelView categoryModelView = new CategoryModelView { Categories = data };
            return View(categoryModelView);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult Create(CategoryModelView category)
        {
            Category cate = new Category { Name = category.Name , Description = category.Description};
            var model = httpClient.PostAsJsonAsync(url, cate).Result;
            return RedirectToAction("Index");
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id)
        {
            try
            {
                var model = httpClient.DeleteAsync(url + id).Result;
                if (model.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return NotFound();
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }
            return View();
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Update(int id)
        {
            var cate = JsonConvert.DeserializeObject<Category>(httpClient.GetStringAsync(url + id).Result);
            CategoryModelView category = new CategoryModelView
            {
                Name = cate.Name,
                Description = cate.Description,
                Id = cate.Id
            };
            return View(category);
        }

        [HttpPost]
        public IActionResult Update(CategoryModelView cate)
        {
            Category category = new Category
            {
                Name = cate.Name,
                Description = cate.Description,
                Id = cate.Id
            };
            var model = httpClient.PutAsJsonAsync(url, category).Result;
            return RedirectToAction("Index");
        }
    }
}

ArtGallery.AdminApp/Controllers/UsermanagerController.cs
using ArtGallery.Data.Entities;
using ArtGallery.ViewModel.System.Admin;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using ArtGallery.AdminApp.Models;
using Microsoft.AspNetCore.Authorization;

namespace ArtGallery.AdminApp.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsermanagerController : Controller
    {
        private readonly string url = "http://localhost:5000/api/UsersManager/";
        private readonly string urlProfile = "http://localhost:5000/api/ProfileManager/";
        private readonly HttpClient httpClient = new HttpClient();

        [HttpGet]
        public IActionResult Index(int pg = 1)
        {
            var model = JsonConvert.DeserializeObject<IEnumerable<Account>>(httpClient.GetStringAsync(url).Result);
            model = model.Where(c => c.Roles != Data.Enum.Roleposition.RAdmin);
            List<UserModelView> userModelView = new List<UserModelView>();
            foreach (var item in model)
            {
                var order = JsonConvert.DeserializeObject<int>(httpClient.GetStringAsync(urlProfile + "GetOrders/" + item.Name).Result);
                var trans = JsonConvert.DeserializeObject<int>(httpClient.GetStringAsync(urlProfile + "GetTransactions/" + item.Name).Result);
                var feedBacks = JsonConvert.DeserializeObject<int>(httpClient.GetStringAsync(urlProfile + "GetFeedBacks/" + item.Name).Result);
                UserModelView view = new UserModelView
                {
                    Name = item.Name,
                    Password = item.Password,
                    Roles = item.Roles,
                    OrdersCount = order,
                    TransactionsCount = trans,
                    FeedBacksCount = feedBacks
                };
                userModelView.Add(view);
            }
            const int pageSize = 10;
            if (pg < 1)
                pg = 1;
            int recsCount = model.Count();
            var pager = new Pager(recsCount, pg, pageSize);
            int recSkip = (pg - 1) * pageSize;
            var data = userModelView.Skip(recSkip).Take(pager.PageSize).ToList();
            this.ViewBag.Pager = pager;
            return View(data);
        }
        //request admin
        [HttpGet]
        public IActionResult RequestAdmin(int pg = 1)
        {
            var model = JsonConvert.DeserializeObject<IEnumerable<Account>>(httpClient.GetStringAsync(url).Result);
            model = model.Where(c => c.Roles == Data.Enum.Roleposition.RAdmin);
            List<UserModelView> userModelView = new List<UserModelView>();
            foreach (var item in model)
            {
                //var cart = JsonConvert.DeserializeObject<int>(httpClient.GetStringAsync(urlProfile + "GetCarts/" + item.Name).Result);
                //var order = JsonConvert.DeserializeObject<int>(httpClient.GetStringAsync(urlProfile + "GetOrders/" + item.Name).Result);
                //var trans = JsonConvert.DeserializeObject<int>(httpClient.GetStringAsync(urlProfile + "GetTransactions/" + item.Name).Result);
                //var feedBacks = JsonConvert.DeserializeObject<int>(httpClient.GetStringAsync(urlProfile + "GetFeedBacks/" + item.Name).Result);
                UserModelView view = new UserModelView
                {
                    Name = item.Name,
                    Password = item.Password,
                    Roles = item.Roles,
                    //CartsCount = cart,
                    //OrdersCount = order,
                    //TransactionsCount = trans,
                    //FeedBacksCount = feedBacks
                };
                userModelView.Add(view);
            }
            const int pageSize = 10;
            if (pg < 1)
                pg = 1;
            int recsCount = model.Count();
            var pager = new Pager(recsCount, pg, pageSize);
            int recSkip = (pg - 1) * pageSize;
            var data = userModelView.Skip(recSkip).Take(pager.PageSize).ToList();
            this.ViewBag.Pager = pager;
            return View(data);
        }
        [HttpGet]
        public async Task<IActionResult> AcceptAdmin(string name)
        {
            var model = JsonConvert.DeserializeObject<bool>(httpClient.GetStringAsync(url + "RequestAdmin/" + name).Result);
            if (model ==true)
            {
                return RedirectToAction("RequestAdmin");
            }
            return BadRequest();
        }
        //
        [HttpPost]
        public IActionResult Index(string name, int pg = 1)
        {
            var model = JsonConvert.DeserializeObject<IEnumerable<Account>>(httpClient.GetStringAsync(url + "searchbyName/" + name).Result);
            List<UserModelView> userModelView = new List<UserModelView>();
            if (model == null)
            {
                return RedirectToAction("Index");
            }
            foreach (var item in model)
            {
                var order = JsonConvert.DeserializeObject<int>(httpClient.GetStringAsync(urlProfile + "GetOrders/" + item.Name).Result);
                var trans = JsonConvert.DeserializeObject<int>(httpClient.GetStringAsync(urlProfile + "GetTransactions/" + item.Name).Result);
                var feedBacks = JsonConvert.DeserializeObject<int>(httpClient.GetStringAsync(urlProfile + "GetFeedBacks/" + item.Name).Result);
                UserModelView view = new UserModelView
                {
                    Name = item.Name,
                    Password = item.Password,
                    Roles = item.Roles,
                    OrdersCount = order,
                    TransactionsCount = trans,
                    FeedBacksCount = feedBacks
                };
                userModelView.Add(view);
            }
            const int pageSize = 10;
            if (pg < 1)
                pg = 1;
            int recsCount = model.Count();
            var pager = new Pager(recsCount, pg, pageSize);
            int recSkip = (pg - 1) * pageSize;
            var data = userModelView.Skip(recSkip).Take(pager.PageSize).ToList();
            this.ViewBag.Pager = pager;
            return View(data);
        }

        [HttpGet]
        public IActionResult Delete(string name)
        {
            try
            {
                
                var model = httpClient.DeleteAsync(url + name).Result;
                if (model.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return NotFound();
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }
            return View();
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Details(string name)
        {
            try
            {
                var model = JsonConvert.DeserializeObject<Account>(httpClient.GetStringAsync(url + name).Result);

                var profile = JsonConvert.DeserializeObject<ProfileUser>(httpClient.GetStringAsync(urlProfile + "getProfileUser/" + name).Result);
                var orders = JsonConvert.DeserializeObject<int>(httpClient.GetStringAsync(urlProfile + "GetOrders/" + model.Name).Result);
                var transactions = JsonConvert.DeserializeObject<int>(httpClient.GetStringAsync(urlProfile + "GetTransactions/" + model.Name).Result);
                var feedBacks = JsonConvert.DeserializeObject<int>(httpClient.GetStringAsync(urlProfile + "GetFeedBacks/" + model.Name).Result);
                ProfileUserModelView userModelView = new ProfileUserModelView
                {
                    FullName = profile.FullName,
                    Gender = profile.Gender,
                    Address = profile.Address,
                    Email = profile.Email,
                    PhoneNumber = profile.PhoneNumber,
                    DOB = profile.DOB,
                    AccountId = profile.AccountId,
                    OrdersCount = orders,
                    TransactionsCount = transactions,
                    FeedBacksCount = feedBacks
                };
                return View(userModelView);
            }
            catch (Exception)
            {
                return View("Error");
            }
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(string name)
        {
            var profile = JsonConvert.DeserializeObject<ProfileUser>(httpClient.GetStringAsync(urlProfile + "getProfileUser/" + name).Result);
            EditProfileReq PuserModelView = new EditProfileReq
            {
                FullName = profile.FullName,
                Gender = profile.Gender,
                Address = profile.Address,
                Email = profile.Email,
                PhoneNumber = profile.PhoneNumber,
                DOB = profile.DOB,
                AccountId = profile.AccountId
            };
            return View(PuserModelView);
        }

        [HttpPost]
        public IActionResult Edit(EditProfileReq puser)
        {
            try
            {
                ProfileUser pro = new ProfileUser 
                { 
                    FullName = puser.FullName,
                    Gender = puser.Gender,
                    Address = puser.Address,
                    Email = puser.Email,
                    PhoneNumber = puser.PhoneNumber,
                    DOB = puser.DOB,
                    AccountId = puser.AccountId
                };
                
                var profile = httpClient.PutAsJsonAsync(urlProfile+ "UpdateProfile/",pro).Result;

                if (profile.IsSuccessStatusCode)
                {
                    return View();
                }

ArtGallery.AdminApp/Views/Usermanager/Edit.cshtml
@using ArtGallery.ViewModel.System.Admin;
@model EditProfileReq
@{
    Layout = "_Layout";
    ViewData["Title"] = "Edit Profile";
}
<hr>
<div class="container bootstrap snippet">
    <div class="row">
        <div class="col-sm-10"><h2>@ViewData["Title"]</h2></div>
    </div>
    <div class="row">
        <div class="col-sm-3">
            <!--left col-->
            <div class="text-center">
                <img src="http://ssl.gstatic.com/accounts/ui/avatar_2x.png" class="avatar img-circle img-thumbnail" alt="avatar">
            </div>
            <br />
        </div><!--/col-3-->
        <div class="col-sm-9">
            <div class="tab-content">
                <div class="tab-pane active" id="home">
                    <form class="form" asp-action="Edit" asp-controller="Usermanager" method="post">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <div class="col-xs-6">
                                <label for="first_name" style="font-size:18px; font-weight:700;">ID</label>
                                <input readonly type="text" class="form-control" asp-for="AccountId">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-xs-6">
                                <label for="first_name" style="font-size:18px; font-weight: 700;">Full Name</label>
                                <input type="text" class="form-control" asp-for="FullName">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-xs-6">
                                <label for="last_name" style="font-size:18px; font-weight: 700;">Gender</label>
                                <input type="text" class="form-control" asp-for="Gender">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-xs-6">
                                <label for="phone" style="font-size:18px; font-weight: 700;">Address</label>
                                <input type="text" class="form-control" asp-for="Address">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-xs-6">
                                <label for="" style="font-size:18px; font-weight: 700;">Email</label>
                                <input type="email" class="form-control" asp-for="Email">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-xs-6">
                                <label for="" style="font-size:18px; font-weight: 700;">Phone Number</label>
                                <input type="text" class="form-control" asp-for="PhoneNumber">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-xs-6">
                                <label for="" style="font-size:18px; font-weight: 700;" class="font-bold">Date of Birth</label>
                                <input type="date" class="form-control" asp-for="DOB">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-xs-12">
                                <div style="padding:4px;"></div>
                                <button class="btn btn btn-success" type="submit">Save</button>&nbsp;&nbsp;
                                @Html.ActionLink("Back To List", "Index", "Usermanager", null, new { @class = "btn btn-secondary" })
                            </div>
                        </div>
                    </form>
                </div><!--/tab-pane-->
            </div><!--/tab-pane-->
        </div><!--/tab-content-->
    </div><!--/col-9-->
</div><!--/row-->
<hr>
<br />

ArtGallery.AdminApp/Views/Usermanager/Index.cshtml
@using ArtGallery.ViewModel.System.Admin;
@model IEnumerable<UserModelView>
@{
    Layout = "_Layout";
    ViewData["Title"] = "User List";
    Pager pager = new Pager();
    int pageNo = 0;
    if (ViewBag.Pager != null)
    {
        pager = ViewBag.Pager;
        pageNo = pager.CurrentPage;
    }
}
<div class="page-heading">
    <div class="page-title">
        <div class="row">
            <div class="col-12 col-md-6 order-md-1 order-last">
                <h3>@ViewData["Title"]</h3>
                <p class="text-subtitle text-muted">For admin to check they list</p>
            </div>
            <div class="col-12 col-md-6 order-md-2 order-first">
                <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">@Html.ActionLink("Dashboard", "Index", "Home")</li>
                        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
    <section class="section">
        <div class="card">
            <div class="card-header">
                <div class="row mb-3">
                    <div class="col-sm-12 col-md-4">
                        <div class="dataTables_length" id="table1_length">
                            <form asp-action="Index" asp-controller="Usermanager" method="post">
                                <h6>Search by Name</h6>
                                <input class="form-control" type="text" name="name" placeholder="Search">
                                <div style="padding:4px;"></div>
                                <input type="submit" value="Search" class="btn btn-success" />
                            </form>
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-3"></div>
                    <div class="col-sm-12 col-md-3"> </div>
                    <div class="col-sm-12 col-md-3"></div>
                </div>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-light mb-0">
                        <thead>
                            <tr>
                                <th class="col-3">@Html.DisplayNameFor(c => c.Name)</th>
                                @*<th>@Html.DisplayNameFor(c => c.Password)</th>*@
                                <th class="col-2">Roles</th>
                                <th class="col-2">Orders</th>
                                <th class="col-4">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.Name</td>
                                    @*<td>@item.Password</td>*@
                                    <td>
                                        @if (item.Roles.ToString() == "Admin")
                                        {
                                            <a class="btn btn-danger">@item.Roles.ToString()</a>
                                        }
                                        else
                                        {
                                            <a class="btn btn-success">@item.Roles.ToString()</a>
                                        }
                                    </td>
                                    <td>
                                        @item.OrdersCount
                                    </td>
                                    <td>
                                        <span onclick="return confirm('Are you sure want to delete this data ?')">
                                            @Html.ActionLink("Delete", "Delete", "UserManager", new { name = item.Name }, new { @class = "btn btn-danger" })
                                        </span>
                                        @Html.ActionLink("Details", "Details", "UserManager", new { name = item.Name }, new { @class = "btn btn-primary" })
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="container">
                @if (pager.TotalPages > 0)
                {
                    <ul class="pagination justify-content-end">
                        @if (pager.CurrentPage > 1)
                        {
                            @*<li class="page-item"><a class="page-link" asp-controller="UserManager" asp-action="Index" asp-route-pg="1">First</a></li>*@
                            <li class="page-item">
                                <a class="page-link" asp-controller="UserManager" asp-action="Index" asp-route-pg="@(pager.CurrentPage - 1)">Previous</a>
                            </li>
                        }
                        @for (var pge = pager.StartPage; pge <= pager.EndPage; pge++)
                        {
                            <li class="page-item @(pge == pager.CurrentPage ? "active" : "")">
                                <a class="page-link" asp-controller="UserManager" asp-action="Index" asp-route-pg="@pge">@pge</a>
                            </li>
                        }
                        @if (pager.CurrentPage < pager.TotalPages)
                        {
                            <li class="page-item">
                                <a class="page-link" asp-controller="UserManager" asp-action="Index" asp-route-pg="@(pager.CurrentPage + 1)">Next</a>
                            </li>
                            @*<li class="page-item">
                            <a class="page-link" asp-controller="CategoryManager" asp-action="Index" asp-route-pg="@(pager.TotalPages)">Last</a>
                        </li>*@
                        }
                    </ul>
                }
            </div>
        </div>
    </section>
</div>
<script src="~/assets/js/bootstrap.bundle.min.js"></script>
<script src="~/assets/vendors/simple-datatables/simple-datatables.js"></script>
<script src="~/assets/js/mazer.js"></script>

ArtGallery.AdminApp/Views/Usermanager/RequestAdmin.cshtml
@using ArtGallery.ViewModel.System.Admin;
@model IEnumerable<UserModelView>
@{
    Layout = "_Layout";
    ViewData["Title"] = "User List";
    Pager pager = new Pager();
    int pageNo = 0;
    if (ViewBag.Pager != null)
    {
        pager = ViewBag.Pager;
        pageNo = pager.CurrentPage;
    }
}
<div class="page-heading">
    <div class="page-title">
        <div class="row">
            <div class="col-12 col-md-6 order-md-1 order-last">
                <h3>@ViewData["Title"]</h3>
                <p class="text-subtitle text-muted">For admin to check they list</p>
            </div>
            <div class="col-12 col-md-6 order-md-2 order-first">
                <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">@Html.ActionLink("Dashboard", "Index", "Home")</li>
                        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
    <section class="section">
        <div class="card">
            <div class="card-header">
                <div class="row mb-3">
                    <div class="col-sm-12 col-md-4">
                        <div class="dataTables_length" id="table1_length">
                            <form asp-action="Index" asp-controller="Usermanager" method="post">
                                <h6>Search by Name</h6>
                                <input class="form-control" type="text" name="name" placeholder="Search">
                                <div style="padding:4px;"></div>
                                <input type="submit" value="Search" class="btn btn-success" />
                            </form>
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-3"></div>
                    <div class="col-sm-12 col-md-3"> </div>
                    <div class="col-sm-12 col-md-3"></div>
                </div>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-light mb-0">
                        <thead>
                            <tr>
                                <th class="col-4">@Html.DisplayNameFor(c => c.Name)</th>
                                <th class="col-2">Roles</th>
                                <th class="col-4">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.Name</td>
                                    <td>
                                        <span onclick="return confirm('Are you sure want to accept account?')">
                                            @Html.ActionLink("Accept", "AcceptAdmin", "UserManager", new { name = item.Name }, new { @class = "btn btn-primary" })
                                        </span>
                                    </td>
                                    @*<td>
                                        @item.CartsCount
                                    </td>
                                    <td>
                                        @item.OrdersCount
                                    </td>
                                    <td>
                                        @item.TransactionsCount
                                    </td>
                                    <td>
                                        @item.FeedBacksCount
                                    </td>*@
                                    <td>
                                        <span onclick="return confirm('Are you sure want to delete this data ?')">
                                            @Html.ActionLink("Delete", "Delete", "UserManager", new { name = item.Name }, new { @class = "btn btn-danger" })
                                        </span>
                                        @Html.ActionLink("Details", "Details", "UserManager", new { name = item.Name }, new { @class = "btn btn-primary" })
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="container">
                @if (pager.TotalPages > 0)
                {
                    <ul class="pagination justify-content-end">
                        @if (pager.CurrentPage > 1)
                        {
                            @*<li class="page-item"><a class="page-link" asp-controller="UserManager" asp-action="Index" asp-route-pg="1">First</a></li>*@
                            <li class="page-item">
                                <a class="page-link" asp-controller="UserManager" asp-action="Index" asp-route-pg="@(pager.CurrentPage - 1)">Previous</a>
                            </li>
                        }
                        @for (var pge = pager.StartPage; pge <= pager.EndPage; pge++)
                        {
                            <li class="page-item @(pge == pager.CurrentPage ? "active" : "")">
                                <a class="page-link" asp-controller="UserManager" asp-action="Index" asp-route-pg="@pge">@pge</a>
                            </li>
                        }
                        @if (pager.CurrentPage < pager.TotalPages)
                        {
                            <li class="page-item">
                                <a class="page-link" asp-controller="UserManager" asp-action="Index" asp-route-pg="@(pager.CurrentPage + 1)">Next</a>
                            </li>
                            @*<li class="page-item">
                                    <a class="page-link" asp-controller="CategoryManager" asp-action="Index" asp-route-pg="@(pager.TotalPages)">Last</a>
                                </li>*@
                        }
                    </ul>
                }
            </div>
        </div>
    </section>
</div>
<script src="~/assets/js/bootstrap.bundle.min.js"></script>
<script src="~/assets/vendors/simple-datatables/simple-datatables.js"></script>
<script src="~/assets/js/mazer.js"></script>